(() => {
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 const categories=[['roman-candles-consumer-fireworks','Roman Candles'],['sound-shells','Sound shells'],['barrages-en','Barrages'],['maximum-load-mortars','Maximum load mortars'],['cakes-bombardos-consumer-fireworks','Multishots Cakes'],['angled-cakes','Angled Cakes'],['fireworks-kits','Fireworks Kits'],['ground-spinners','Ground Spinners'],['fountains','Fountains'],['sparklers-consumer-fireworks','Sparklers'],['miscellaneous','Miscellaneous']];
 const allowed=['image/jpeg','image/png','image/webp','image/gif'],preview=location.hostname==='localhost'||location.hostname==='127.0.0.1';
 let state={data:null,sha:null,editing:-1,file:null,dirty:false,admins:[],currentAdmin:'',currentUser:null};
 const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
 async function api(path,options={}){const r=await fetch('/.netlify/functions/'+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const b=await r.json().catch(()=>({error:'Unexpected server response'}));if(!r.ok)throw new Error(b.error||'Request failed');return b}
 async function boot(){
  if(preview&&new URLSearchParams(location.search).has('preview')){const r=await fetch('/data/site.json');state.data=await r.json();state.sha='preview';showDashboard();$('#save-all').disabled=true;$('#save-status').textContent='Local preview mode';return}
  try{const a=await api('admin-auth');if(a.authenticated)await load()}catch{}
 }
 $('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const f=new FormData(e.currentTarget);try{await api('admin-auth',{method:'POST',body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),username:f.get('username'),password:f.get('password')})});await load()}catch(err){$('#login-error').textContent=err.message}});
 async function load(){const r=await api('admin-data');state.data=r.data;state.sha=r.sha;showDashboard()}
 function showDashboard(){$('#login-view').hidden=true;$('#dashboard').hidden=false;fillContact();renderProducts();loadAdmins()}
 function fillContact(){$$('[data-field]').forEach(i=>{i.value=state.data[i.dataset.field]||'';i.addEventListener('input',()=>{state.data[i.dataset.field]=i.value;dirty()})})}
 function dirty(){state.dirty=true;$('#save-status').textContent='Unsaved changes'}
 function renderProducts(){const q=$('#admin-search').value.toLowerCase().trim(),items=state.data.products.map((p,i)=>({p,i})).filter(({p})=>!q||[p.name,p.code,p.type,p.price,p.inventory].some(v=>String(v??'').toLowerCase().includes(q)));$('#product-summary').textContent=`${items.length} of ${state.data.products.length} products`;
  $('#product-list').innerHTML=items.map(({p,i})=>`<article class="product-row"><img class="thumb" src="${escapeAttr(p.image)}" alt=""><div><div class="product-name">${escapeHtml(p.name)}</div><div class="product-meta">${escapeHtml(p.code?`Code ${p.code} · ${p.type}`:p.type)}</div></div><div class="price">${escapeHtml(p.price||'Call for price')}<small class="inventory ${p.inventory===0?'sold-out':''}">${p.inventory==null?'Inventory not tracked':p.inventory===0?'Sold out':`${p.inventory} in stock`}</small></div><span class="badge ${p.active===false?'off':''}">${p.active===false?'Hidden':'Published'}</span><div class="row-actions"><button class="secondary" data-edit="${i}">Edit</button><button class="danger" data-delete="${i}">Remove</button></div></article>`).join('')||'<div class="panel">No products match your search.</div>'}
 $('#admin-search').addEventListener('input',renderProducts);$('#product-list').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openProduct(Number(edit.dataset.edit));if(del&&confirm(`Remove ${state.data.products[Number(del.dataset.delete)].name}?`)){state.data.products.splice(Number(del.dataset.delete),1);dirty();renderProducts()}});
 $('#add-product').addEventListener('click',()=>openProduct(-1));
 function openProduct(index){state.editing=index;state.file=null;const p=index<0?{name:'',code:'',category:categories[0][0],type:'',price:'',inventory:null,details:'',active:true,image:''}:state.data.products[index];$('#modal-title').textContent=index<0?'Add product':'Edit product';const f=$('#product-form');['name','code','category','type','price','details','image'].forEach(k=>f.elements[k].value=p[k]||'');f.elements.inventory.value=p.inventory==null?'':p.inventory;f.elements.active.checked=p.active!==false;$('#photo-preview').src=p.image||'';$('#photo-file').value='';$('#product-dialog').showModal()}
 const select=$('#product-form').elements.category;select.innerHTML=categories.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');
 $('#photo-file').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!allowed.includes(file.type)){e.target.value='';return toast('Only JPG, PNG, WebP, and GIF images are allowed')}if(file.size>5*1024*1024){e.target.value='';return toast('Image must be smaller than 5 MB')}state.file=file;$('#photo-preview').src=URL.createObjectURL(file)});
 $('#product-form').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){return $('#product-dialog').close()}const f=e.currentTarget,button=$('#save-product');button.disabled=true;button.textContent='Saving…';try{let image=f.elements.image.value;if(state.file){if(preview)image=URL.createObjectURL(state.file);else{const data=await toDataUrl(state.file);const r=await api('admin-media',{method:'POST',body:JSON.stringify({filename:state.file.name,mimeType:state.file.type,data})});image=r.path}}const inventory=f.elements.inventory.value===''?null:Number(f.elements.inventory.value);if(inventory!==null&&(!Number.isInteger(inventory)||inventory<0))throw new Error('Inventory must be a whole number of 0 or more');const product={name:f.elements.name.value.trim(),code:f.elements.code.value.trim(),category:f.elements.category.value,type:f.elements.type.value.trim(),price:f.elements.price.value.trim(),inventory,details:f.elements.details.value.trim(),theme:'blue',active:f.elements.active.checked,image};if(!product.name)throw new Error('Product name is required');if(state.editing<0)state.data.products.unshift(product);else state.data.products[state.editing]=product;dirty();renderProducts();$('#product-dialog').close();toast('Product saved locally—publish changes when ready')}catch(err){toast(err.message)}finally{button.disabled=false;button.textContent='Save product'}});
 async function loadAdmins(){try{if(preview){state.currentAdmin='owner';state.currentUser={username:'owner',firstName:'Preview',lastName:'Owner',displayName:'Preview Owner'};state.admins=[{username:'owner',firstName:'Preview',lastName:'Owner',displayName:'Preview Owner',role:'Owner',protected:true},{username:'store-manager',firstName:'Store',lastName:'Manager',displayName:'Store Manager',role:'Administrator',protected:false}]}else{const r=await api('admin-users');state.admins=r.users;state.currentAdmin=r.current;state.currentUser=r.currentUser}renderCurrentUser();renderAdmins()}catch(err){toast(err.message)}}
 function renderCurrentUser(){const name=state.currentUser?.displayName||state.currentAdmin||'Administrator';const hello=$('#hello-admin'),logged=$('#logged-in-as');if(hello)hello.textContent=`Hello ${name}`;if(logged)logged.textContent=`Logged in as ${name}`}
 function renderAdmins(){$('#admin-list').innerHTML=state.admins.map(u=>`<article class="admin-row"><div><div class="admin-user">${escapeHtml(u.displayName||u.username)}${u.username===state.currentAdmin?' (you)':''}</div><div class="admin-role">${escapeHtml(u.role)} · ${escapeHtml(u.username)}${u.createdAt?` · Added ${new Date(u.createdAt).toLocaleDateString()}`:''}</div></div><span class="badge ${u.protected?'':'off'}">${u.protected?'Protected owner':'Administrator'}</span><div class="admin-actions">${u.protected?'':`<button class="secondary" data-reset-admin="${escapeHtml(u.username)}">Reset password</button>${u.username===state.currentAdmin?'':`<button class="danger" data-remove-admin="${escapeHtml(u.username)}">Remove</button>`}`}</div></article>`).join('')}
 $('#add-admin').addEventListener('click',()=>{$('#admin-form').reset();$('#admin-dialog').showModal()});
 $('#admin-form').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return $('#admin-dialog').close();if(preview)return toast('Account changes are disabled in preview mode');const f=new FormData(e.currentTarget),b=$('#create-admin');b.disabled=true;b.textContent='Creating…';try{await api('admin-users',{method:'POST',body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),username:f.get('username'),password:f.get('password')})});$('#admin-dialog').close();await loadAdmins();toast('Administrator added')}catch(err){toast(err.message)}finally{b.disabled=false;b.textContent='Create administrator'}});
 $('#admin-list').addEventListener('click',async e=>{const remove=e.target.closest('[data-remove-admin]'),reset=e.target.closest('[data-reset-admin]');if(!remove&&!reset)return;if(preview)return toast('Account changes are disabled in preview mode');const username=(remove||reset).dataset[remove?'removeAdmin':'resetAdmin'];try{if(remove){if(!confirm(`Remove administrator ${username}?`))return;await api('admin-users',{method:'DELETE',body:JSON.stringify({username})});toast('Administrator removed')}else{const password=prompt(`Enter a new password for ${username} (minimum 12 characters):`);if(!password)return;await api('admin-users',{method:'PUT',body:JSON.stringify({username,password})});toast('Password reset')}await loadAdmins()}catch(err){toast(err.message)}});
 $$('.nav-item').forEach(b=>b.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));const view=b.dataset.view;$('#products-view').hidden=view!=='products';$('#contact-view').hidden=view!=='contact';$('#admins-view').hidden=view!=='admins';$('#view-title').textContent={products:'Products',contact:'Contact details',admins:'Administrators'}[view];if(view==='admins')loadAdmins()}));
 $('#save-all').addEventListener('click',async()=>{if(preview)return;const b=$('#save-all');b.disabled=true;b.textContent='Publishing…';try{const r=await api('admin-data',{method:'PUT',body:JSON.stringify({data:state.data,sha:state.sha})});state.sha=r.sha;state.dirty=false;$('#save-status').textContent='Published';toast('Changes published. Netlify is rebuilding the website.')}catch(err){toast(err.message)}finally{b.disabled=false;b.textContent='Save changes'}});
 $('#logout').addEventListener('click',async()=>{if(!preview)await api('admin-auth',{method:'DELETE'});location.reload()});
 addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});boot();
 function escapeHtml(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escapeAttr(v){return escapeHtml(v)}function toDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
})();
